using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using VerisqAI.API.Models;

namespace VerisqAI.API.Services
{
    public class PdfService
    {
        public byte[] GenerateVendorReport(Vendor vendor, Scorecard scorecard, List<Finding> findings)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    // header
                    page.Header().Column(col =>
                    {
                        col.Item().Text("VERISQ AI REPORT")
                            .FontSize(22)
                            .Bold()
                            .FontColor(Colors.Blue.Darken2);

                        col.Item().Text("Vendor Risk Assessment")
                            .FontSize(12)
                            .FontColor(Colors.Grey.Darken1);
                    });

                    // main content
                    page.Content().Column(col =>
                    {
                        col.Spacing(15);

                        // vendor Info Card
                        col.Item().Container().Padding(10).Border(1).Column(c =>
                        {
                            c.Item().Text($"Vendor: {vendor.Name}").Bold();
                            c.Item().Text($"Domain: {vendor.Domain}");
                        });

                        // Score Section
                        col.Item().Container().Padding(10).Border(1).Column(c =>
                        {
                            c.Item().Text("Risk Summary").Bold().FontSize(14);

                            c.Item().Text($"Score: {scorecard.Score}");
                            c.Item().Text($"Risk Score: {scorecard.RiskScore}");
                            c.Item().Text($"Risk Tier: Tier {scorecard.RiskTier}");
                        });

                        // Findings Section
                        col.Item().Text("Findings").Bold().FontSize(14);

                        var critical = findings.Where(f => f.Severity == Models.Enums.FindingSeverity.Critical).ToList();
                        var high = findings.Where(f => f.Severity == Models.Enums.FindingSeverity.High).ToList();
                        var medium = findings.Where(f => f.Severity == Models.Enums.FindingSeverity.Medium).ToList();

                        void AddSection(string title, List<Finding> list, string color)
                        {
                            if (!list.Any()) return;

                            col.Item().Text(title).Bold().FontColor(color);

                            foreach (var f in list)
                            {
                                col.Item().Container().Padding(8).Border(1).Column(c =>
                                {
                                    c.Item().Text(f.Title).Bold();
                                    c.Item().Text(f.Description ?? "");
                                });
                            }
                        }

                        AddSection("🔴 Critical", critical, Colors.Red.Darken2);
                        AddSection("🟠 High", high, Colors.Orange.Darken2);
                        AddSection("🟡 Medium", medium, Colors.Yellow.Darken3);

                        if (!findings.Any())
                        {
                            col.Item().Text("No findings 🎉").FontColor(Colors.Green.Darken2);
                        }
                    });

                    // FOOTER
                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by Verisq AI");
                    });
                });
            }).GeneratePdf();
        }
    }
}